# Generated by Django 2.1.15 on 2020-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0004_user_details'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='tokenblocklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.CharField(blank=True, db_column='User', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLOYEE_ID', models.IntegerField()),
                ('FIRST_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('LAST_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('WORK_EMAIL', models.CharField(blank=True, max_length=100, null=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
                ('USERNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=100, null=True)),
                ('ROLE', models.CharField(blank=True, max_length=100, null=True)),
                ('PROJECT', models.CharField(blank=True, max_length=100, null=True)),
                ('APP_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('IS_ACTIVE', models.BooleanField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
