# Generated by Django 2.1 on 2020-11-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0004_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaktest_failed_img_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_column='Date', max_length=20, null=True)),
                ('station', models.CharField(db_column='STATION', max_length=20, null=True)),
                ('plant_code', models.CharField(db_column='PLANT_CODE', max_length=200, null=True)),
                ('plant_name', models.CharField(db_column='PLANT_NAME', max_length=200, null=True)),
                ('line', models.CharField(db_column='LINE', max_length=200, null=True)),
                ('img_url', models.CharField(db_column='IMG_URL', max_length=200, null=True)),
                ('uploaded_by', models.CharField(db_column='UPLOADED_BY', max_length=200, null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', null=True)),
                ('worker_at_line', models.CharField(db_column='PERSON_AT_LINE', max_length=200, null=True)),
                ('updated_by', models.CharField(db_column='UPDATED_BY', max_length=200, null=True)),
            ],
        ),
    ]
