# Generated by Django 2.1.15 on 2020-11-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0005_leaktest_failed_img_details'),
        ('dfp', '0005_leaktest_failed_img_details_tokenblocklist_userinfo'),
    ]

    operations = [
    ]
