# Generated by Django 2.1.15 on 2020-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0006_merge_20201112_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='backtracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(db_column='PLANT_NAME', max_length=200, null=True)),
                ('plant_code', models.CharField(db_column='PLANT_CODE', max_length=200, null=True)),
                ('line', models.CharField(db_column='LINE', max_length=200, null=True)),
                ('leak_test_img_url', models.CharField(db_column='IMG_URL', max_length=200, null=True)),
                ('upload_time', models.DateTimeField(blank=True)),
                ('matched_c4_fp_img_url', models.CharField(db_column='MATCHED_C4_FP_IMG_URL', max_length=200, null=True)),
                ('matched_c4_fp_time', models.DateTimeField(blank=True)),
                ('matched_c3_fp_img_url', models.CharField(db_column='MATCHED_C3_FP_IMG_URL', max_length=200, null=True)),
                ('matched_c3_fp_time', models.DateTimeField(blank=True)),
                ('matched_c2_fp_img_url', models.CharField(db_column='MATCHED_C2_FP_IMG_URL', max_length=200, null=True)),
                ('matched_c2_fp_time', models.DateTimeField(blank=True)),
                ('matched_c1_left_fp_img_url', models.CharField(db_column='MATCHED_C1_LEFT_FP_IMG_URL', max_length=200, null=True)),
                ('matched_c1_left_fp_time', models.DateTimeField(blank=True)),
                ('matched_c4_right_fp_img_url', models.CharField(db_column='MATCHED_C1_RIGHT_FP_IMG_URL', max_length=200, null=True)),
                ('matched_c4_right_fp_time', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leaktest_failed_img_details',
            name='is_active',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True, null=True),
        ),
    ]
