# Generated by Django 2.1.15 on 2020-11-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfp', '0008_auto_20201112_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtracking',
            old_name='matched_c4_right_fp_img_url',
            new_name='matched_c1_right_fp_img_url',
        ),
        migrations.RenameField(
            model_name='backtracking',
            old_name='matched_c4_right_fp_time',
            new_name='matched_c1_right_fp_time',
        ),
        migrations.AddField(
            model_name='backtracking',
            name='leak_test_type',
            field=models.CharField(db_column='LEAK_TEST_TYPE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaktest_failed_img_details',
            name='leak_test_type',
            field=models.CharField(db_column='LEAK_TEST_TYPE', max_length=20, null=True),
        ),
    ]
